// action - Get CONTRACT reducer
export const GET_CONTRACT_SUCCESS = "GET_CONTRACT_SUCCESS";
export const GET_CONTRACT_ERROR = "GET_CONTRACT_ERROR";
export const GET_CONTRACT = "GET_CONTRACT";

// action - Get CONTRACTS reducer
export const GET_CONTRACTS_SUCCESS = "GET_CONTRACTS_SUCCESS";
export const GET_CONTRACTS_ERROR = "GET_CONTRACTS_ERROR";
export const GET_CONTRACTS = "GET_CONTRACTS";

// action - Update CONTRACT reducer
export const CREATE_CONTRACT_SUCCESS = "CREATE_CONTRACT_SUCCESS";
export const CREATE_CONTRACT_ERROR = "CREATE_CONTRACT_ERROR";
export const CREATE_CONTRACT = "CREATE_CONTRACT";

// action - Update CONTRACT reducer
export const UPDATE_CONTRACT_SUCCESS = "UPDATE_CONTRACT_SUCCESS";
export const UPDATE_CONTRACT_ERROR = "UPDATE_CONTRACT_ERROR";
export const UPDATE_CONTRACT = "UPDATE_CONTRACT";