export const CREATE_METADATA_REQUEST = "CREATE_METADATA_REQUEST";
export const CREATE_METADATA_SUCCESS = "CREATE_METADATA_SUCCESS";
export const CREATE_METADATA_ERROR = "CREATE_METADATA_ERROR";

export const GET_ALL_METADATA = "GET_ALL_METADATA";
export const GET_ALL_METADATA_SUCCESS = "GET_ALL_METADATA_SUCCESS";
export const GET_ALL_METADATA_ERROR = "GET_ALL_METADATA_ERROR";
