// action - Get Musicians reducer
export const GET_MUSICIANS_SUCCESS = "GET_MUSICIANS_SUCCESS";
export const GET_MUSICIANS_ERROR = "GET_MUSICIANS_ERROR";
export const GET_MUSICIANS = "GET_MUSICIANS";

export const GET_MUSICIAN = "GET_MUSICIAN";
export const GET_MUSICIAN_SUCCESS = "GET_MUSICIAN_SUCCESS";
export const GET_MUSICIAN_ERROR = "GET_MUSICIAN_ERROR";

// action - Update Musician reducer
export const UPDATE_MUSICIAN_SUCCESS = "UPDATE_MUSICIAN_SUCCESS";
export const UPDATE_MUSICIAN_ERROR = "UPDATE_MUSICIAN_ERROR";
export const UPDATE_MUSICIAN = "UPDATE_MUSICIAN";

// action - Get Musician members reducer
export const GET_MUSICIAN_MEMBERS_SUCCESS = "GET_MUSICIAN_MEMBERS_SUCCESS";
export const GET_MUSICIAN_MEMBERS_ERROR = "GET_MUSICIAN_MEMBERS_ERROR";
export const GET_MUSICIAN_MEMBERS = "GET_MUSICIAN_MEMBERS";

// action - Add Musician member reducer
export const ADD_MUSICIAN_MEMBER_SUCCESS = "ADD_MUSICIAN_MEMBER_SUCCESS";
export const ADD_MUSICIAN_MEMBER_ERROR = "ADD_MUSICIAN_MEMBER_ERROR";
export const ADD_MUSICIAN_MEMBER = "ADD_MUSICIAN_MEMBER";
