export const CREATE_ROLE_REQUEST = "CREATE_ROLE_REQUEST";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_ERROR = "CREATE_ROLE_ERROR";

export const GET_ALL_ROLE = "GET_ALL_ROLE";
export const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
export const GET_ALL_ROLE_ERROR = "GET_ALL_ROLE_ERROR";

export const GET_ROLE_BY_TENANT = "GET_ROLE_BY_TENANT";
export const GET_ROLE_BY_TENANT_SUCCESS = "GET_ROLE_BT_TENANT_SUCCESS";
export const GET_ROLE_BY_TENANT_ERROR = "GET_ROLE_TENANT_ERROR";
