export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST'
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS'
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR'

export const GET_ALL_ROLE = 'GET_ALL_ROLE'
export const GET_ALL_ROLE_SUCCESS = 'GET_ALL_ROLE_SUCCESS'
export const GET_ALL_ROLE_ERROR = 'GET_ALL_ROLE_ERROR'