export const CREATE_TENANT_REQUEST = 'CREATE_TENANT_REQUEST'
export const CREATE_TENANT_SUCCESS = 'CREATE_TENANT_SUCCESS'
export const CREATE_TENANT_ERROR = 'CREATE_TENANT_ERROR'

export const GET_ALL_TENANT = 'GET_ALL_TENANT'
export const GET_ALL_TENANT_SUCCESS = 'GET_ALL_TENANT_SUCCESS'
export const GET_ALL_TENANT_ERROR = 'GET_ALL_TENANT_ERROR'